### ISSUE TITLE
tecplot文件里面可以包含除了单纯流场以外的其他东西吗？ 比如燃烧和颗粒

### ISSUE THREAD

**Issue by daxueliuying** [jingchangshi/tec2cgns#1]

**Comment by jingchangshi** [comment]
你可以看下`fortran/src/sol_tec.dat`文件，按照Tecplot格式，第一行是`Variables=x,y,cell,order_cell,partition_id,Rho,U,V,P,Mach`，比如`Mach`就是自定义的变量，你的燃烧、颗粒只要按照Tecplot格式写出来，就让`tec2cgns.f90`按照类似的方式读写就好了。

**Comment by daxueliuying** [comment]
这样子，谢谢哈，我是想用把燃烧的文件转成cgns格式，因为用的软件没有这个格式导出，只能想中间途径了
